version: '2'

services:
  web:
    build: .
    volumes:
      - ./logs:/var/logs
      - ./sites:/var/www/html
      - ./conf:/etc/nginx/conf.d
    ports:
      - 80:80
  phpserver:
    image: php:fpm
    volumes:
      - ./sites:/var/www/html
